# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5335840d9090087e1e8f1660f60a7ce293511089cf4987a784ac5870b8c09aa3422d2961bbf8f5a5276bfeaf867562d9b0c9d25c358b2aebb2724afa69e297d1

test:
  secret_key_base: 95322d9c10237e9cc579eae62dc0e5e12183d45d77a269dfc573585cfc64f58eaba503c21b909b6d7d23c8575ed517af33cc2cd075a321eea9f9350c47b28278

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
